### ISSUE TITLE
Bug: (a large number of errors when using SDK in Xcode)

### ISSUE THREAD

**Issue by donutcube** [kinde-oss/kinde-sdk-ios#14]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

When I try to build a simple hello world ios app that has the Kinde SDK added via pods I get a bunch of errors and the build fails.

Please see the following video for what I'm talking about.

https://github.com/kinde-oss/kinde-sdk-ios/assets/144574434/48839df0-54da-47d9-987a-38010451c837

### Library URL

https://github.com/kinde-oss/kinde-sdk-ios

### Library version

1.2.0

### Operating system(s)

macOS

### Operating system version(s)

14.4.1

### Additional information

The steps to reproduce:

1. Create new ios app in xcode
2. Follow the steps to add kinde ios sdk https://kinde.com/docs/developer-tools/ios-sdk/
3. Go to build the app
4. See warnings about the build
5. Opt to do the suggested updates mentioned from xcode
6. Build then fails with the error shown in the video

**Comment by wahabniazi56** [comment]
This is not only our SDK pod error. Once you add any other Cocoapods like Alamofire, KingFisher or any other this error occurs with latest Xcode so far. you just need to disable "ENABLE_USER_SCRIPT_SANDBOXING" from build setting. This issue already raised on Cocoapods github repo (https://github.com/CocoaPods/CocoaPods/issues/11946) once Cocoapods update that it would be automatically resolved.

**Comment by onderay** [comment]
@donutcube given the above comments, are you able to confirm being able to resolve the errors?
