### ISSUE TITLE
Feature request: (use Swift Package Manager instead of cocoapods)

### ISSUE THREAD

**Issue by donutcube** [kinde-oss/kinde-sdk-ios#15]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

Removing the additional complexity of cocoapods by being able to add the kinde ios sdk via swift package manager.

### What solution would you like to see?

Adding your ios sdk through the xcode interface rather than using cocoapods.

**Comment by DanielRivers** [comment]
The package is now available on the swift package manager https://swiftpackageindex.com/kinde-oss/kinde-sdk-ios
