### ISSUE TITLE
Feature request: Expose Raw Id Token

### ISSUE THREAD

**Issue by ahoran3** [kinde-oss/kinde-sdk-ios#21]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

I need access to the raw id token for use with internal token exchange system. Currently, only the access token is exposed through this SDK. Part of why I need the ID token is to access to the email and profile information. I am aware there is a call to `getUserDetails` which pulls the information from the id token, but I need the full Id token _with_ this information embedded. 

### What solution would you like to see?

Could you expose an argument on `getToken` to allow the user to specify if they want the idToken or the accessToken. This method should default to return the accessToken so as to not break existing behavior.

I am a not an iOS developer by trade, so my syntax may not be accurate. Please consider below pseudo code. :)
```diff
- // returns only access token type
- public func getToken() async throws -> String 

+ // could return either access token or id token depending on what caller specifies
+ public func getToken(type: TokenType = .accessToken) async throws -> String

 ```

or expose a new method for `getIdToken()` which returns only the raw idToken.

Many thanks!

### Additional information

Several other kinde SDKs in  your ecosystem expose the raw id token through a method call. 

_P.S. The documentation on https://docs.kinde.com/ is very well put together! 👏_

**Comment by DanielRivers** [comment]
Released under 1.4.0
